#!/bin/bash -e

source /etc/os-release

while read -r line; do
	if ! read -r pkgbase > /dev/null 2>&1 < "${line%/vmlinuz}/pkgbase"; then
		# if the kernel has no pkgbase, we skip it
		continue
	fi

	# remove sd-boot entries
	for type in default fallback recovery; do
		entry="$ID-$pkgbase-$type"
		if [[ -f "boot/loader/entries/$entry.conf" ]]; then
			printf '  Removing entry of %s (%s)\n' "$pkgbase" "$type"
			rm -f "boot/loader/entries/$entry.conf"
		fi
	done
done
