#!/bin/bash
if [[ $(id -u) != 0 ]]; then
	echo "Run this as root"
	exit
fi
cd /
rm boot/loader/entries/*-linux-*.conf
find lib/modules -maxdepth 3 -type f -name 'vmlinuz' | /usr/share/libalpm/scripts/sd-boot
